# Generated by Django 3.2.6 on 2021-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('dueDate', models.DateTimeField()),
            ],
        ),
    ]
